services:
    ciqual.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { id: 'exact', origgpfr: 'ipartial', origfdnm: 'ipartial' } ]
        tags: [ 'api_platform.filter' ]