AppBundle\Entity\Ciqual:
    type: entity
    table: ciqual
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        origgpcd:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        origgpfr:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        origfdcd:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        origfdnm:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        energieReglementUeNum11692011Kj100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: energie_reglement_ue_num_1169_2011_kj_100g
        energieReglementUeNum11692011Kcal100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: energie_reglement_ue_num_1169_2011_kcal_100g
        energieNXFacteurJonesAvecFibresKj100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: energie_n_x_facteur_jones_avec_fibres_kj_100g
        energieNXFacteurJonesAvecFibresKcal100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: energie_n_x_facteur_jones_avec_fibres_kcal_100g
        eauG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: eau_g_100g
        proteinesG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: proteines_g_100g
        proteinesBrutesNX625G100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: proteines_brutes_n_x_625_g_100g
        glucidesG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: glucides_g_100g
        lipidesG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: lipides_g_100g
        sucresG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: sucres_g_100g
        amidonG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: amidon_g_100g
        fibresAlimentairesG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: fibres_alimentaires_g_100g
        polyolsTotauxG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: polyols_totaux_g_100g
        cendresG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: cendres_g_100g
        alcoolG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: alcool_g_100g
        acidesOrganiquesG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: acides_organiques_g_100g
        agSaturesG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: ag_satures_g_100g
        agMonoinsaturesG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: ag_monoinsatures_g_100g
        agPolyinsaturesG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: ag_polyinsatures_g_100g
        ag40ButyriqueG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: ag_40_butyrique_g_100g
        ag60CaproiqueG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: ag_60_caproique_g_100g
        ag80CapryliqueG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: ag_80_caprylique_g_100g
        ag100CapriqueG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: ag_100_caprique_g_100g
        ag120LauriqueG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: ag_120_laurique_g_100g
        ag140MyristiqueG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: ag_140_myristique_g_100g
        ag160PalmitiqueG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: ag_160_palmitique_g_100g
        ag180SteariqueG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: ag_180_stearique_g_100g
        ag1819cN9OleiqueG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: ag_181_9c_n9_oleique_g_100g
        ag1829c12cN6LinoleiqueG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: ag_182_9c12c_n6_linoleique_g_100g
        ag183C9c12c15N3AlphalinoleniqueG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: ag_183_c9c12c15_n3_alphalinolenique_g_100g
        ag2045c8c11c14cN6ArachidoniqueG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: ag_204_5c8c11c14c_n6_arachidonique_g_100g
        ag2055c8c11c14c17cN3EpaG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: ag_205_5c8c11c14c17c_n3_epa_g_100g
        ag2264c7c10c13c16c19cN3DhaG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: ag_226_4c7c10c13c16c19c_n3_dha_g_100g
        cholesterolMg100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: cholesterol_mg_100g
        selChlorureDeSodiumG100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: sel_chlorure_de_sodium_g_100g
        calciumMg100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: calcium_mg_100g
        chlorureMg100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: chlorure_mg_100g
        cuivreMg100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: cuivre_mg_100g
        ferMg100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: fer_mg_100g
        iodeMicrog100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: iode_microg_100g
        magnesiumMg100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: magnesium_mg_100g
        manganeseMg100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: manganese_mg_100g
        phosphoreMg100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: phosphore_mg_100g
        potassiumMg100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: potassium_mg_100g
        seleniumMicrog100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: selenium_microg_100g
        sodiumMg100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: sodium_mg_100g
        zincMg100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: zinc_mg_100g
        retinolMicrog100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: retinol_microg_100g
        betacaroteneMicrog100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: betacarotene_microg_100g
        vitamineDMicrog100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: vitamine_d_microg_100g
        vitamineEMg100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: vitamine_e_mg_100g
        vitamineK1Microg100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: vitamine_k1_microg_100g
        vitamineK2Microg100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: vitamine_k2_microg_100g
        vitamineCMg100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: vitamine_c_mg_100g
        vitamineB1OuThiamineMg100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: vitamine_b1_ou_thiamine_mg_100g
        vitamineB2OuRiboflavineMg100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: vitamine_b2_ou_riboflavine_mg_100g
        vitamineB3OuPpOuNiacineMg100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: vitamine_b3_ou_pp_ou_niacine_mg_100g
        vitamineB5OuAcidePantotheniqueMg100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: vitamine_b5_ou_acide_pantothenique_mg_100g
        vitamineB6Mg100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: vitamine_b6_mg_100g
        vitamineB9OuFolatesTotauxMicrog100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: vitamine_b9_ou_folates_totaux_microg_100g
        vitamineB12Microg100g:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: vitamine_b12_microg_100g
    lifecycleCallbacks: {  }
